#! /usr/bin/env bash

GITHUB_NAME=plus7wist
UPSTREAM_NAME=GeekUniversity
GITHUB_REPO=Frontend-05-Template
GITHUB_TOKEN=
WEEK=1

main() {
	if [ $# -ne 1 ]; then
        fail "usage: comment <week-no>"
	fi
	WEEK="$1"

    if [ ! -d "$(week_name)" ]; then
        fail "not found week $(week_name)"
    fi

	printf 'your token: '
	read -r GITHUB_TOKEN
	printf "\nuse token: '%s'\n" "$GITHUB_TOKEN"

    echo "body: '$(comment_body)'"
	while true; do
        comment_issue && break
		sleep 3
	done
}

fail() {
	printf 'error: %s\n' "$1"
	exit 1
}

week_name() {
	printf "week-%02d" "$WEEK"
}

comment() {
	echo -n '#学号: G20200447050163\n'
	echo -n '#姓名: 张世权\n'
	echo -n '#班级: 5\n'
	echo -n '#小组: 5\n'
    echo -n "#作业&总结链接: https://github.com/$GITHUB_NAME/$GITHUB_REPO/tree/master/$(week_name)\n"
}

comment_body() {
    printf '{"body": "%s"}' "$(comment)"
}

comment_issue() {
    curl \
        -u $GITHUB_NAME:$GITHUB_TOKEN \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/$UPSTREAM_NAME/$GITHUB_REPO/issues/$WEEK/comments \
        -d "$(comment_body)"
}

main "$@"
